### ISSUE TITLE
Confirm before installing guessed package name

### ISSUE THREAD

**Issue by flip111** [purescript/spago#570] opened 2020-02-14 16:42 UTC
```
» spago install purescript-debug
[warn] The package 'purescript-debug' was not found in your package set, but 'debug' was. Using that instead.
[info] Installing 1 dependencies.
[info] Searching for packages cache metadata..
[info] Unable to find packages cache metadata, downloading from GitHub..
[info] Installing and globally caching "debug"
[info] Installation complete.
```

https://github.com/garyb/purescript-debug

https://github.com/Unisay/purescript-binary/blob/master/src/Debug.purs

**Comment by flip111** [comment] 2020-02-14 16:45
I think actually the right package as installed in this case but it wasn't loaded yet. Anyway i leave this open because i think it will be useful.

**Comment by f-f** [comment] 2020-02-17 09:12
@flip111 I'd like to understand more the situation you were in: it sounds like you were in the IDE, then installed a library, and expected the IDE to pick it up, but it didn't happen until you did a `spago build`. Is this correct?

If that's the case, then I think it'd make sense to automatically build a library that is being installed with `spago install $library`.

Re asking for confirmation when dropping the `purescript-` prefix: I'm not keen on this, and the reason is that it would be a net usability regression: the renaming happens only if it's actually the same package, so I think there would be no point (and an unnecessary step) in asking for confirmation about something that the user already expressed when typing `spago install some-package`

**Comment by flip111** [comment] 2020-02-17 11:04
I was have `spago build --watch` then `spago install purescript-debug` in another terminal window.

From the warning i understood that some heuristic was being done. It's quite a strong warning

> [warn] The package 'purescript-debug' was not found in your package set, but 'debug' was. Using that instead.

But if it's not some text-searching function but instead just about the `purescript-` prefix, maybe instead something like

> [Info] 'purescript-debug' was resolved to the 'debug' package

**Comment by f-f** [comment] 2020-02-17 12:04
@flip111 good points.

I opened:
- #572 to track the fact that the watcher should pick up new packages
- #571 to make that warning milder - I'll consider that a fix for this issue

**Closed** 2020-02-17 18:40 UTC
