### ISSUE TITLE
Trouble using local package_set

### ISSUE THREAD

**Issue by jeslie0** [purescript/spago#1088] opened 2023-10-15 19:32 UTC
I don't seem to be able to use local package sets with spago-0.93.14. I have run `spago init` and changed my `spago.yaml` to the following:

```yaml
package:
  dependencies:
    - console
    - effect
    - prelude
  name: test
  test:
    dependencies: []
    main: Test.Main
workspace:
  extra_packages: {}
  package_set:
    path: ./packages.json
```

Running `spago build` presents me with the following error:
```
❌ Couldn't parse Spago config, error:
  An error occurred while decoding a JSON value:
  Under 'Config':
  At object key workspace:
  Under 'WorkspaceConfig':
  At object key package_set:
  Under 'SetFromUrl':
  At object key url:
  No value was found.
```

Are local package sets allowed? The [custom-package-sets](https://github.com/purescript/spago#custom-package-sets) seems to imply that this is allowed, but it isn't mentioned in the [workspace](https://github.com/purescript/spago#the-workspace) section at all.

**Comment by f-f** [comment] 2023-10-15 19:34
0.93.14 does not support the `path` key. Could you upgrade to the latest one? (0.93.18)

**Comment by jeslie0** [comment] 2023-10-15 20:06
It doesn't look like version 0.93.18 is available easily for Nix yet. I can have a look when https://github.com/thomashoneyman/purescript-overlay is updated.

**Comment by f-f** [comment] 2023-10-15 20:18
Indeed. That's the tracking issue to get it up to speed: https://github.com/thomashoneyman/purescript-overlay/issues/47

We also have an in-progress flake at #981 

I'll close as I believe the issue is fixed with latest

**Closed by f-f** 2023-10-15 20:18 UTC

**Comment by thomashoneyman** [comment] 2023-10-15 21:07
The issue with getting it in purescript-overlay is that none of the Spago releases are happening on GitHub, so the overlay isn't picking them up. I'm back from PTO now and can look at reading out NPM releases instead.
