### ISSUE TITLE
please allow mirror like replace the github.com by sourcehut.sr or self-host.gitea.com

### ISSUE THREAD

**Issue by dG94Cg** [purescript/spago#890] opened 2022-06-10 15:02 UTC
there is some network issue at using spago, and here is some bad situaiton like there is no allow for foreign network access.
is there some fork or commit to allow spago to use a mirror repository? my company won't allow me to access github while i'm coding.

now i init the project at my personal pc and copy it into my work pc. but is there some way to use mirror? like set the `env GIT_SOURCE=mirror.gitea.com spago init/build/repl `

**Comment by f-f** [comment] 2022-06-10 20:59
Is this a duplicate of #795? Does the solution described there help you with this?

**Closed** 2023-01-20 17:29 UTC
