### ISSUE TITLE
new project generate with test.dhall

### ISSUE THREAD

**Issue by flip111** [purescript/spago#605] opened 2020-04-07 13:42 UTC
In these docs https://github.com/purescript/spago#devdependencies-testdependencies-or-in-general-a-situation-with-many-configurations

The sentence

> You might have a simpler situation than a monorepo

Threw me off like i had some situations to choose from. One being using `testDependencies` and the other one separate configuration files. From what i understood later using separate configuration files is the only way to do it.

Since `spago init` is generating a test direction with a stub file, could it also generate a `test.dhall` file?

**Comment by f-f** [comment] 2020-04-12 11:03
Yes! This is a duplicate of #416, which I intend to implement

**Closed by f-f** 2020-04-12 11:03 UTC
