### ISSUE TITLE
Spago can't find the latest package set

### ISSUE THREAD

**Issue by JamieBallingall** [purescript/spago#753] opened 2021-03-16 23:49 UTC
If I run `spago init` (with spago version 0.19.1 and purs version 0.14.0) I get:
```
[info] Initializing a sample project or migrating an existing one..
[info] Updating package-set tag to "psc-0.14.0-20210316"
Fetching the new one and generating hashes.. (this might take some time)
[warn] Package-set tag "psc-0.14.0-20210316" in the repo "purescript/package-sets" does not exist.
Will ignore user-specified tag and continue using current tag: "psc-0.13.8-20210118"
[info] Set up a local Spago project.
[info] Try running `spago build`
```
Note the failure to find `psc-0.14.0-20210316`. While this is just a warning it causes some major issues down the line because you have mismatch between compiler and package set. A similar problem occurs when running `spago upgrade-set` on an existing project. I'm opening the issue here because I haven't been able to replicate the problem with `psc-package`, although I may have missed something there.

**Comment by darichey** [comment] 2021-03-17 06:01
I believe this is caused by https://github.com/purescript/package-sets/issues/870

**Comment by f-f** [comment] 2021-03-17 08:52
That's right, fixed with [a new release](https://github.com/purescript/package-sets/releases/tag/psc-0.14.0-20210317)

**Closed by f-f** 2021-03-17 08:52 UTC
