### ISSUE TITLE
A command to add remote/local packages

### ISSUE THREAD

**Issue by wclr** [purescript/spago#808] opened 2021-08-03 10:58 UTC
What do you think about the command for adding remote repo packages like:

```
spago add https://github.com/Unisay/purescript-facebook
```

spago could read remote `bower.json` (or `spago.dhall` if exsists) for the dependencies list and the name.

and would automatically do what described here: https://github.com/purescript/spago#add-a-package-to-the-package-set

```
let upstream = -- <package set URL here>
in  upstream
  with facebook =
    { dependencies =
        [ "console"
        , "aff"
        , "prelude"
        , "foreign"
        , "foreign-generic"
        , "errors"
        , "effect"
        ]
    , repo =
        "https://github.com/Unisay/purescript-facebook.git"
    , version =
        "v0.3.0"  -- branch, tag, or commit hash
    }
```

This could also work for adding local packages like:
```
spago add ./my-package --name override-pkg-name
```
if locates `spago.dhall` would add to `packages.dhall`:

```
with  override-pkg-name =  ./my-package/spago.dhall as Location
```

**Comment by f-f** [comment] 2021-08-03 15:38
Is this a duplicate of #404?

**Comment by wclr** [comment] 2021-08-03 21:01
I believe the kind of.

**Closed** 2023-09-20 18:17 UTC
Labels: new command, UX
