### ISSUE TITLE
spago test fails from parent folder

### ISSUE THREAD

**Issue by JohnGurin** [purescript/spago#941] opened 2023-02-04 15:07 UTC
```
Windows 11, cmd
purs --version 0.15.7
spago --version 0.20.9
```
```
parent\prj1> spago init
```
```
parent> spago -x ./prj1/spago.dhall test
```
creates `.spago` in `parent` with `prj1` dependencies, but results in
```
[error] Module 'Test.Main' not found! Are you including it in your build?
```
The goal is to have single `.spago` for all sub projects with overlapping dependencies and the same `purescript` version  in `packages.dhall`. If I use spago inside projects, it creates tons of equal files for every folder. Do I configure parent `spago.dhall` `packages.dhall` somehow to achieve such functionality?

**Comment by JohnGurin** [comment] 2023-02-04 19:04
As a semi-workaround, a symbolic link to parent `.spago`. But all commands are run from inside project folders
```cmd
parent\prj1> mklink /D .spago ..\.spago
parent\prj1> mklink /D output ..\output
```
`output` symlink allows to reuse compiled files as well. As far as I understand, even though `Test.Main` modules have the same name in all sub folders, they get recompiled with `spago test`.

**Comment by f-f** [comment] 2023-02-06 09:32
You have committed some changes to the new spago line (versions from `0.90` up), so I assume you have switched to using the new one?
If that's the case you don't need to use symbolic links. You can have a `spago.yaml` that defines a `workspace` in `parent`, and have `spago.yaml` files with a `package` in the the subfolders like `prj1`.
Then running `spago build -p prj1` should to the right thing.

**Comment by JohnGurin** [comment] 2023-02-06 11:24
Cannot make it working. `spago 0.92.9` `purs 0.15.7`
```yaml
# c:\parent\spago.yaml
workspace:
  extra_packages:
    prj1:
      path: "./prj1"
```
```
c:\parent\prj1>spago init
c:\parent\prj1>cd ..
c:\parent>spago build -p prj1
Refreshing the Registry Index...
Reading Spago workspace configuration...
Selected package prj1 was not found in the local packages.
Available packages:
```
By the way, where can I read the discussion about moving from `dhall` to `yaml`, if any?
And is there a documentation for `yaml` configuration?

**Comment by f-f** [comment] 2023-02-06 12:41
@JohnGurin you should not specify `prj1` in the top-level config.

This is how `parent/spago.yaml` could look like (note, you can add a `package` section in here too if you want a package at the top level):
```yaml
workspace:
  package_set:
    registry: 2.2.0
```

and this is the one in `parent/prj1/spago.yaml`:
```yaml
package:
  name: prj1
  dependencies:
  - effect
  - prelude
```

> where can I read the discussion about moving from dhall to yaml, if any?

This comment has some background (but I will put together more documentation once things are more stable): https://github.com/purescript/spago/issues/842#issuecomment-1262935534

> And is there a documentation for yaml configuration?

There is no documentation yet, as `spago@next` is currently in `pre-alpha` state.
The alpha release is being worked on, and will ship with documentation.

**Comment by JohnGurin** [comment] 2023-02-06 12:55
Still...
```
c:\parent>spago build -p prj1 -v
CWD: c:\parent
Global cache: "C:\\Users\\John\\AppData\\Local\\spago-nodejs\\Cache"
Local cache: "c:\\parent\\.spago"
Refreshing the Registry Index...
Found https://github.com/purescript/registry-index.git locally, pulling...
Found https://github.com/purescript/registry.git locally, pulling...
Reading Spago workspace configuration...
Reading config from spago.yaml
Ignored some of the glob matches as they are gitignored: ["prj1/spago.yaml"]
Selected package prj1 was not found in the local packages.
Available packages:
```

**Comment by f-f** [comment] 2023-02-06 15:26
Can you share a reproducing example so I can have a look at it?

**Comment by JohnGurin** [comment] 2023-02-06 16:49
[parent.zip](https://github.com/purescript/spago/files/10665330/parent.zip)

**Comment by f-f** [comment] 2023-02-06 17:10
It works for me if I `git init` before calling spago, does that fix it for you?

**Comment by JohnGurin** [comment] 2023-02-06 17:22
Yes. Thanks!
It works when `parent` is a git repo.
I tried `parent` without `.git` right at `C:\` level, so there were no upper repos.

**Comment by JohnGurin** [comment] 2023-02-06 17:25
What if someone uses something different from `git`?

**Comment by JohnGurin** [comment] 2023-02-06 20:37
I split the issue, so there are two: one for `spago` and one for `spago@next`.
Tried `spago@0.20.9` with `parent` folder being a git repo - still no luck.
The initial comment of the issue https://github.com/purescript/spago/issues/941#issue-1570982805

**Comment by f-f** [comment] 2023-02-06 20:40
This workflow is not as easy to achieve as with `spago@next`, but you can still configure it to share the `packages.dhall`, have a look [at the docs on monorepos](https://github.com/purescript/spago#monorepo).

**Comment by f-f** [comment] 2023-02-08 22:22
I will close it now as it looks like the docs cover this aspect, but let's reopen if we find out that there is indeed a bug in handling this scenario.

**Closed by f-f** 2023-02-08 22:22 UTC
