### ISSUE TITLE
--config doesn’t take absolute paths

### ISSUE THREAD

**Issue by Profpatsch** [purescript/spago#597] opened 2020-03-17 23:00 UTC
lol

```
    ${pkgs.spago}/bin/spago --config ${dummy-spago.dhall} docs --deps-only --open
```

```
spago: 
Error: Invalid input

(input):1:3:
  |
1 | .//nix/store/zxplllgww80l2fb26adgzmnca0g3g7x1-spago.dhall
  |   ^
unexpected '/'
expecting expression or whitespace
```

**Comment by f-f** [comment] 2020-03-17 23:23
Duplicate of #472, and there's a WIP fix in #505

**Closed** 2020-03-17 23:46 UTC
