### ISSUE TITLE
Error: Dynamic require of "fs" is not supported

### ISSUE THREAD

**Issue by ad-si** [purescript/spago#885] opened 2022-05-15 14:10 UTC
When I build https://github.com/feramhq/transity with following command:
```sh
spago bundle-app \
  --platform=node \
  --minify
```

And try to execute it like `node index.js`, I get following error:

```txt
Error: Dynamic require of "fs" is not supported
    at file:///Users/adrian/Dropbox/Projects/transity/index.js:1:418
    at file:///Users/adrian/Dropbox/Projects/transity/index.js:10:59752
    at file:///Users/adrian/Dropbox/Projects/transity/index.js:1:498
    at file:///Users/adrian/Dropbox/Projects/transity/index.js:13:53377
    at file:///Users/adrian/Dropbox/Projects/transity/index.js:1:498
    at file:///Users/adrian/Dropbox/Projects/transity/index.js:86:1476
    at ModuleJob.run (node:internal/modules/esm/module_job:175:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)
    at async handleMainPromise (node:internal/modules/run_main:63:12)
```

How can this be fixed? Do I need to configure esbuild somehow?

**Comment by f-f** [comment] 2022-05-15 14:25
@sigma-andex any idea about this?

**Comment by sigma-andex** [comment] 2022-05-15 16:36
@ad-si can you push the branch where you have the changes?

**Comment by ad-si** [comment] 2022-05-15 18:33
@sigma-andex Should already have been pusht to master! 🤔

**Comment by CarstenKoenig** [comment] 2022-06-07 09:32
Hi I already commented in the [discourse-thread](https://discourse.purescript.org/t/purescript-0-15-spago-affjax/3045/6) and I hope you don't mind me repeating it here.

For me it seems as if **spago** is asking `esbuild`  to produce ESM:

    [debug] Running command: `esbuild --platform=node --format=esm --bundle --outfile=test.js`

when I do a bundle and I guess it gets confused here - if I don't include the `--format=esm` flag the bundled-output works fine - at least in the scenario form the discourse thread.

**Comment by f-f** [comment] 2023-09-29 21:20
@ad-si could you try bundling this with `spago@next` to see if the issue is still present?

**Comment by f-f** [comment] 2023-10-14 12:15
I'll close this as I think this is now solve, but let's reopen it if it turns out it's not

**Closed by f-f** 2023-10-14 12:15 UTC

**Comment by ad-si** [comment] 2024-01-11 16:59
Yes, works! Thanks for your efforts! 😊
