### ISSUE TITLE
`spago -x` cannot parse Windows paths

### ISSUE THREAD

**Issue by ozkutuk** [purescript/spago#832] opened 2021-12-22 18:38 UTC
```bash
$ spago init
$ spago -x .\spago.dhall build
spago.exe:
Error: Invalid input

(input):1:4:
  |
1 | ./.\spago.dhall
  |    ^
unexpected '\'
expecting "", "", "", "", '/', ->, //, //\\, /\, :, end of input, keyword, operator, or whitespace
```

**Comment by f-f** [comment] 2021-12-23 01:19
I suspect this is a duplicate of #472, where the bug is in this line?
https://github.com/purescript/spago/blob/8ce19ea5648f8bd65d6db88428bac56e66cf2560/src/Spago/Config.hs#L115

I suspect that we can get around this by patching the path in Dhall's Options and calling `inputExprWithOpts` instead of `inputExpr` here

**Comment by f-f** [comment] 2023-09-20 18:01
The new Spago does now allow for passing in alternate configuration files, so this does not apply anymore.

**Closed by f-f** 2023-09-20 18:01 UTC
Labels: bug
