### ISSUE TITLE
Spago doesn't globally cache packages that use spago

### ISSUE THREAD

**Issue by simonolander** [purescript/spago#703] opened 2020-11-22 09:35 UTC
|Operative system|Spago version|
|---|---|
|macOS 10.15.5|0.17.0|

I've noticed that the global cache for spago at _~/.cache/spago_ only seems to contain bower packages. Any package that uses spago.dhall leaves an empty directory. 
Example:
```
$ tree ~/.cache/spago/halogen*
~/.cache/spago/halogen
~/.cache/spago/halogen-formless
~/.cache/spago/halogen-vdom
└── v6.1.3
    ├── GUIDE.md
    ├── LICENSE
    ├── README.md
    ├── bower.json
    ├── index.html
    ├── package.json
    ├── src
    │   └── Halogen
    │       ├── VDom
    │       │   ├── DOM
    │       │   │   └── Prop.purs
    │       │   ├── DOM.purs
    │       │   ├── Machine.purs
    │       │   ├── Thunk.purs
    │       │   ├── Types.purs
    │       │   ├── Util.js
    │       │   └── Util.purs
    │       └── VDom.purs
    └── test
        ├── Main.js
        └── Main.purs
```
When running the `spago install -v` we see that it seems to attempt to globally cache _halogen_ and _halogen-formless_ as well, but it doesn't seem to work.
```
$ spago install -v
...
[debug] Fetching package halogen
[debug] Directory ".spago/__download-halogen-v5.1.0-67ee1bb8e495e2bf/download" does not exist, creating...
[debug] Fetching package halogen-formless
[debug] Directory ".spago/halogen" does not exist, creating...
[debug] Running `globallyCache`: PackageName {packageName = "halogen"} https://github.com/slamdata/purescript-halogen.git v5.1.0
[debug] Directory ".spago/__download-halogen-formless-v1.0.0-a6f3416ae37f31e5/download" does not exist, creating...
[debug] Directory ".spago/halogen-formless" does not exist, creating...
[debug] Running `globallyCache`: PackageName {packageName = "halogen-formless"} https://github.com/thomashoneyman/purescript-halogen-formless.git v1.0.0
[debug] Fetching package halogen-vdom
[info] Copying from global cache: "halogen-vdom"
[info] Installing "halogen-formless"
[info] Installing "halogen"
[debug] Directory ".spago/halogen-vdom" does not exist, creating...
```
Ideally, spago should support globally caching spago packages as well.

**Comment by f-f** [comment] 2020-12-22 18:43
This sounds like a bug - are you able to put together a small reproduction so I can look at this?

**Comment by simonolander** [comment] 2020-12-29 14:20
Sure!

One fairly easy way to reproduce the behavior is to create a new project and install `halogen`, but I think it works with any dependency that's not bower. Doing the following gives you the output seen above:
```bash
# create a new project
mkdir spago-issue-703
cd spago-issue-703
spago init

# install a package not using bower
spago install halogen

# remove local cash and reinstall verbosely
rm -rf .spago
spago install -v

# delete the project (when done)
cd ..
rm -rf spago-issue-703
```

**Comment by f-f** [comment] 2020-12-30 01:09
@simonolander oh wow, this is terrible - thanks for the repro! I'll look into this ASAP

**Comment by f-f** [comment] 2020-12-31 08:31
@simonolander it looks like I cannot reproduce anymore :thinking:

**Comment by simonolander** [comment] 2021-01-11 08:34
Okay, I'll double check the repro actually works for me and get back to you.

**Comment by f-f** [comment] 2021-04-07 13:40
I'll close this as we're not able to replicate - let's reopen it if there are any news on this front

**Closed by f-f** 2021-04-07 13:40 UTC
Labels: needs repro
