### ISSUE TITLE
Problem with suggested "dev" yarn script in "Get started from scratch with Parcel (frontend projects)" section

### ISSUE THREAD

**Issue by danny-andrews** [purescript/spago#619] opened 2020-04-15 16:27 UTC
In the [Get started from scratch with Parcel (frontend projects)](https://github.com/purescript/spago#get-started-from-scratch-with-parcel-frontend-projects) section, under step 6, it recommends the following yarn script:

```json
...
  "scripts": {
    "dev": "spago build --watch & parcel index.html",
  },
...
```

When I run this script on my project, I get the following console output:

```
yarn run v1.22.4
$ spago bundle-app --watch --to dist/index.js & parcel index.html
[info] Installation complete.
spago: <stdin>: hGetLine: end of file
Server running at http://localhost:1234
✨  Built in 3.96s.
```

Everything builds fine, but it fails to do a rebuild when I change a source file. Is the use of the `&` environment-dependent? I'm not very shell-literate, so excuse my ignorance.

In another guide I recall it suggesting that you run `spago build --watch` in a separate shell tab which is what I've been doing, but I thought I would leave an issue for anyone else having the same problem and maybe we can add a note to the docs to help people along.

**Comment by f-f** [comment] 2020-04-20 11:46
I think this might be a duplicate of #567?

**Closed** 2020-04-20 13:31 UTC

**Comment by danny-andrews** [comment] 2020-04-20 15:29
Yep, it is a dupe.
