### ISSUE TITLE
Check existence of module before passing it to esbuild

### ISSUE THREAD

**Issue by flip111** [purescript/spago#1170] opened 2024-01-18 11:03 UTC
This works (as expected)
```
» spago bundle --module MyProject.Main --pedantic-packages --platform browser --verbose-stats                                                                                                                                         28 files, 1287 ins.(+), 7042 del.(-) 1 [12:01:34]
Reading Spago workspace configuration...

✅ Selecting package to build: timey

Downloading dependencies...
Building...
           Src   Lib   All
Warnings     0     0     0
Errors       0     0     0

✅ Build succeeded.

Looking for unused and undeclared transitive dependencies...
Bundling...

  index.js  1.2mb ⚠️

⚡ Done in 59ms

✅ Bundle succeeded.
```

Without giving module name you get this
```
» spago bundle --pedantic-packages --platform browser --verbose-stats
Reading Spago workspace configuration...

✅ Selecting package to build: timey

Downloading dependencies...
Building...
           Src   Lib   All
Warnings     0     0     0
Errors       0     0     0

✅ Build succeeded.

Looking for unused and undeclared transitive dependencies...
Bundling...
✘ [ERROR] Could not resolve "./output/Main/index.js"

    <stdin>:1:21:
      1 │ import { main } from './output/Main/index.js'; main();
        ╵                      ~~~~~~~~~~~~~~~~~~~~~~~~

1 error

❌ Failed to bundle.
```

Would be nice to have a message like: `Could not find module "Main", perhaps you want to specify a module as entrypoint using the --module flag`

**Comment by f-f** [comment] 2024-01-18 11:09
I think this is a duplicate of #181 (which is about finding the `main` function in the selected module, which does require that we find the module first)

**Closed by f-f** 2024-01-18 11:09 UTC
