### ISSUE TITLE
Feature request: Decline build if modules from indirect dependencies are imported

### ISSUE THREAD

**Issue by thought2** [purescript/spago#415] opened 2019-09-21 04:37 UTC
Currently one can use all the modules that are indirect dependencies of the direct dependencies. It would be a bit nicer, if we could just use the modules that are explicitly declared.

**Comment by f-f** [comment] 2019-09-21 10:39
Yes, this would be a nice to have! A way we could do it would be to:
- generate a mapping from "module" and "package" as described in https://github.com/spacchetti/spago/issues/165 (note: we wouldn't need to download all the packages in the set, but only all the transitive dependencies of the project, which we already do)
- expand the project globs
- parse the beginning of these with [a small parser for import declarations](https://github.com/jmackie/purescript.nix/blob/2d87289f22bc0f823033fb59c16df6009de09038/elaborator/src/PureScript.hs)
- complain if we find any module that comes from a package that is not in the project dependencies

**Comment by Dretch** [comment] 2019-09-27 12:15
Perhaps there could also be a error or a warning when packages are in the dependency list but are not actually directly imported.

**Comment by Benjmhart** [comment] 2019-11-07 15:28
I can try and tackle this one over the next week or two

**Comment by hdgarrood** [comment] 2019-11-17 22:48
As it happens there is an issue for this inside the compiler https://github.com/purescript/purescript/issues/3493, and I think it might be preferable to do this inside the compiler rather than in Spago. Although having said this, the work we are looking at in that issue is going to be quite a bit more involved than what is being discussed here, so perhaps it's a good stopgap anyway.

**Comment by Benjmhart** [comment] 2019-11-22 03:29
@f-f I'm looking at implementation on this one now that I've had some time to examine. this and the referenced issue https://github.com/spacchetti/spago/issues/165 - it seems like this is blocked until we do something with the ideas in https://github.com/spacchetti/spago/issues/165

**Comment by f-f** [comment] 2020-03-29 21:01
I just realized this is a duplicate of #598, I'll close this one as the new one is more up to date

**Closed by f-f** 2020-03-29 21:01 UTC
Labels: UX, feature, good second issue, help wanted
