### ISSUE TITLE
Spago errors when used with Yarn 2 Plug'n'Play

### ISSUE THREAD

**Issue by mhmdanas** [purescript/spago#564] opened 2020-02-03 16:43 UTC
Using Plug'n'Play (PnP) with Yarn 2, I get the following error whenever trying to run `spago`:
```
/Users/mhmdanas/Desktop/projecteuler-solutions/.yarn/unplugged/spago-npm-0.13.1-4737e24f3e/node_modules/spago/spago:1
����


SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.module_1.Module._load (/Users/mhmdanas/Desktop/projecteuler-solutions/.pnp.js:24865:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
```
However, it still works on Yarn 1 PnP.

**Comment by f-f** [comment] 2020-02-03 21:41
Thanks for the report @mhmdanas! I'm not sure how I can try to reproduce this, could you post more info about exactly which version of yarn you have installed, and how I have to configure it to have it use PnP? Then is it enough to call any spago command to trigger this?

**Comment by mhmdanas** [comment] 2020-02-04 03:11
Sorry for not giving a reproduction; I was in a hurry.
To reproduce:
1. Install Yarn 2: `npm i -g yarn@berry`
2. Create project with the following `package.json`:
```json
{
  "installConfig": {
    "pnp": true
  },
  "devDependencies": {
    "purescript": "^0.13.6",
    "spago": "^0.13.1"
  }
}
```
3. Try running any spago command; even `yarn spago` errors

On a related note, it seems the issue here is not with spago, but with Yarn. Trying to run PureScript directly gives a very similar error:
```
/Users/mhmdanas/Desktop/spago-yarn2-pnp-error/.yarn/unplugged/purescript-npm-0.13.6-7f5d88f564/node_modules/purescript/purs.bin:1
����


SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.module_1.Module._load (/Users/mhmdanas/Desktop/spago-yarn2-pnp-error/.pnp.js:15172:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
```
Perhaps Yarn 2 PnP doesn't play well with native executables. Should I open an issue there?

**Comment by f-f** [comment] 2020-02-04 11:52
@mhmdanas thanks for the repro and for investigating this further! Yeah, if `purs` is also affected then it looks like this is a Yarn bug and should be reported there :slightly_smiling_face:

**Comment by mhmdanas** [comment] 2020-02-04 19:23
It seems an issue was already opened for this: yarnpkg/berry#882.
But according to one of the members, it's a wontfix; see https://github.com/yarnpkg/berry/issues/882#issuecomment-581180752.

**Comment by hdgarrood** [comment] 2020-02-04 19:53
I have no intention of changing the purescript compiler npm package to work with yarn 2 pnp, especially since it’s not clear to me that this is even possible. I’m not sure the concern they have of non-portability really applies here, because our postinstall scripts ensure that the appropriate binary is installed. Personally I don’t really care enough to make this case to the yarn maintainers that supporting binaries which aren’t written in JS is valuable, but it might be nice if someone else were to do it.

**Comment by mhmdanas** [comment] 2020-02-06 15:16
Quote from the issue:

>  At worst, you can make a JS script that uses `execFileSync`.

Perhaps this might be the right way to make it work with Yarn 2 PnP.

I'd like to make a PR for this, but I'm not knowledgeable enough to do so.

**Comment by hdgarrood** [comment] 2020-02-06 15:25
> At worst, you can make a JS script that uses execFileSync.

Oh right okay, thanks - although, the purescript compiler npm package used to use a separate JS wrapper script, but it makes the repl behave weirdly, presumably because all input and output is going via an unnecessary node process. I never dug into it properly becaues having the npm package point at the binary directly fixed the issue. 

> If there is neither intention nor real benefit to supporting Yarn 2 PnP, I'll close this issue.

I should clarify that I am only talking about the purescript compiler npm package (which points directly to a binary in a similar way). What spago does is up to @f-f :)

**Comment by f-f** [comment] 2020-02-06 17:44
I'd say that it does make sense to keep `purs` and `spago` policies synced on this, mostly because:
- we have `spago repl`, and that might suffer from the same problems @hdgarrood mentioned above
- I think it's of little use to users if `spago` can be installed with PnP but `purs` cannot

This said, I'm fine with any option here: if someone contributes a fix that doesn't cause problems with the repl and that works for both `purs` and `spago` then it would be great, but I'm also open to call this a "wontfix" if that's where `purs` wants to go

**Comment by mhmdanas** [comment] 2020-02-07 11:48
> I should clarify that I am only talking about the purescript compiler npm package (which points directly to a binary in a similar way). What spago does is up to @f-f :)

Oh, right, sorry for the confusion.

I'd like to help with this since it's relevant to me. Additionally, Yarn is recommended by [the recommended tooling thread in Discourse](https://discourse.purescript.org/t/recommended-tooling-for-purescript-applications-in-2019/948) and PnP is going to be the default instead of `node_modules` in Yarn v2. So I'd appreciate a little guidance on fixing this issue.

**Comment by mhmdanas** [comment] 2020-02-07 11:49
Sorry, closed by mistake.

**Comment by hdgarrood** [comment] 2020-02-07 13:01
Yes, I think moving to Discourse is appropriate.

**Comment by mhmdanas** [comment] 2020-02-07 16:22
OK... so I created an account and got the 'Basic' badge, but I can't find how to post. Do I still not have the privilege, or is it something else? (I'm sorry if it is something obvious)

**Comment by thomashoneyman** [comment] 2020-02-07 17:00
@mhmdanas Sorry about that — your post had just the link to this issue, and Discourse is careful about new users who post just a link. I’ve approved the post and it’s live now.

I think it would help get more action on that thread if you added some of the context of this thread to the post directly.

**Comment by mhmdanas** [comment] 2020-02-07 17:55
Created the Discourse post: https://discourse.purescript.org/t/issue-spago-errors-when-used-with-yarn-2-plugnplay/1133?u=mhmdanas.
Also added some context as @thomashoneyman suggested.

**Comment by f-f** [comment] 2020-03-29 20:58
Following the discussion on Discourse it looks like:
- the issue is still a wontfix for the Yarn team
- it doesn't really seem like there are any good solutions for workarounds so that Purs and Spago could use them
- the "recommended tooling" post has been edited to recommend NPM over Yarn

Given the above I'd say we cannot really do much about all of this, so I'll close this issue - however let's revisit it if the situation changes and/or we get some new ideas on how to take care of this

**Closed by f-f** 2020-03-29 20:58 UTC

**Comment by mhmdanas** [comment] 2020-04-07 09:40
BTW, I just wanted to say that I dug a little bit deeper, and it seems even when using Yarn 2 with the good old `node_modules`, it still gives the same error. So I edited the issue's title to reflect that.
