### ISSUE TITLE
Setup new project

### ISSUE THREAD

**Issue by flip111** [purescript/spago#1166] opened 2024-01-15 14:37 UTC
I noticed the new readme does not have this section yet https://github.com/purescript/spago-legacy#get-started-from-scratch-with-parcel-frontend-projects 

Some questions from my side:
1. is parcel still the recommended tool? JS system changes so fast i don't know how alternative tools compare
2. Probably the code in the old guide has to be modified as it was suffering from this old issue https://discourse.purescript.org/t/parcel-2-hot-reload-duplicates-page/2670/3

**Comment by f-f** [comment] 2024-01-15 20:40
Duplicate of #1002, let's continue the discussion there

**Closed by f-f** 2024-01-15 20:40 UTC
