### ISSUE TITLE
Allow --purs-args to be passed to 'purs bundle'

### ISSUE THREAD

**Issue by felixSchl** [purescript/spago#580] opened 2020-02-25 01:36 UTC
For `spago bundle-app` and `spago bundle-module` it is currently impossible to pass arguments straight down to `purs`. We're running into extremely long build times on Circle CI due to PureScript detects more cores than are actually available. We get around that by setting `--purs-args='+RTS -N2 -RTS'`. However, this only works for `spago build`, not for the bundle commands (https://github.com/purescript/spago/blob/083ef16c052a18cb421fe1d74d6d0cda378bea8d/src/Spago/Build.hs#L280). To highlight the severity of the issue, for our project bundeling without those flags takes somewhere between 17 and 20 minutes, whereas with the flag set it only takes about 45 seconds. We are temporarily falling back to just invoking `purs` directly for bundling.

**Comment by f-f** [comment] 2020-03-29 21:02
I just realized this is a duplicate of #216, I'll close this one as that has more info

**Closed by f-f** 2020-03-29 21:02 UTC
Labels: defect, good first issue, help wanted
